version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - url_shortener_php
            - url_statistic_php
    url_shortener_php:
        build: ./images/php
        links:
            - url_shortener_mysql
        volumes:
            - ./www/url-shortener.loc:/var/www/url-shortener.loc
    url_shortener_mysql:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
         - ./etc/mysql:/etc/mysql
         - ./logs/mysql:/var/log/mysql
         - ./mysql:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
         - ./data/url_shortener.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: url_shortener
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    url_statistic_php:
        build: ./images/php
        links:
            - url_statistic_mysql
        volumes:
            - ./www/url-statistic.loc:/var/www/url-statistic.loc
    url_statistic_mysql:
        image: mariadb:latest
        ports:
            - "3360:3306"
        volumes:
            - ./etc/mysql:/etc/mysql
            - ./logs/mysql:/var/log/mysql
            - ./mysqli:/var/lib/mysql
            - ./mysql-files:/var/lib/mysql-files
            - ./data/url_statistic.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: url_statistic
            MYSQL_USER: user
            MYSQL_PASSWORD: user